const youtubedl = require('youtube-dl-exec')

/**
 * Fetches metadata information from a YouTube video or playlist
 * WITHOUT downloading the media.
 *
 * Why this exists:
 * - Avoids repeated calls to YouTube
 * - Allows caching info locally
 * - Reduces request aggressiveness (anti-block)
 *
 * @param {string | URL} url
 *   YouTube video or playlist URL
 *
 * @param {Object} [flags={}]
 *   Optional yt-dlp flags (will override defaults)
 *
 * @returns {Promise<Object>}
 *   Parsed metadata JSON returned by yt-dlp
 */
const getInfo = (url, flags = {}) => {
    return youtubedl(url, {
        /* Core behavior */
        dumpSingleJson: true,   // Return metadata as JSON
        skipDownload: true,    // Do NOT download media

        /* Anti-block strategy */
        sleepInterval: 3,      // Minimum seconds between requests
        maxSleepInterval: 8,   // Random delay upper bound
        retries: 2,            // Low retry count (less fingerprinting)
        fragmentRetries: 2,    // Same logic for fragments
        socketTimeout: 30,     // Network stability
        concurrentFragments: 1, // No parallel fragment downloads

        /* Realistic browser fingerprint */
        userAgent:
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',

        ...flags
    })
}

/**
 * Downloads a YouTube video using a previously saved metadata JSON file.
 *
 * Why this exists:
 * - Separates "info extraction" from "download"
 * - Reduces YouTube requests
 * - Prevents repeated scraping
 *
 * @param {string} infoFile
 *   Path to the JSON file generated by getInfo()
 *
 * @param {Object} [flags={}]
 *   Optional yt-dlp flags (format, output, etc.)
 *
 * @returns {Promise<void>}
 */
const fromInfo = (infoFile, flags = {}) => {
    return youtubedl.exec('', {
        loadInfoJson: infoFile, // Load metadata from disk

        /* Same anti-block profile as getInfo */
        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        concurrentFragments: 1,

        ...flags
    })
}

module.exports = {
    getInfo,
    fromInfo
}
