const youtubedl = require('youtube-dl-exec');
const path = require('path');

/**
 * Absolute path to the cookies file used for authenticated YouTube access.
 *
 * Notes:
 * - In local development, this file may live inside the repository.
 * - In production environments (e.g. Render), this file SHOULD be provided
 *   as a Secret File and will be mounted at `/etc/secrets/<filename>`.
 *
 * Example (Render):
 *   /etc/secrets/cookies.txt
 *
 * IMPORTANT:
 * This file contains browser session cookies and must NEVER be committed
 * to version control.
 */
const COOKIES_PATH =
    process.env.NODE_ENV === 'production'
        ? '/etc/secrets/cookies.txt'
        : path.join(__dirname, 'cookies.txt');

/**
 * Fetches metadata from a YouTube video or playlist WITHOUT downloading media.
 *
 * This function:
 * - Returns metadata as JSON.
 * - Forces Node.js as the JavaScript runtime for yt-dlp.
 * - Applies multiple anti-blocking strategies to reduce detection.
 * - Automatically detects playlists.
 * - Optionally uses cookies for authenticated or restricted content.
 *
 * Typical use cases:
 * - Metadata caching
 * - Playlist inspection
 * - Previewing content before download
 *
 * @param {string | URL} url
 *   The YouTube video or playlist URL.
 *
 * @param {Object} [flags={}]
 *   Optional yt-dlp flags that override the defaults.
 *
 * @returns {Promise<Object>}
 *   Parsed metadata JSON returned by yt-dlp.
 */
const getInfo = (url, flags = {}) => {
    const isPlaylist = url.includes('playlist') || url.includes('list=');

    return youtubedl(url, {
        dumpSingleJson: true,
        skipDownload: true,
        jsRuntimes: 'node',

        /* Anti-block strategy */
        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        socketTimeout: 30,
        concurrentFragments: 1,

        /* Browser fingerprint */
        userAgent:
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',

        /* Flatten playlist entries unless full URLs are required */
        ...(isPlaylist ? { flatPlaylist: true } : {}),

        /* Use cookies if available */
        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),

        ...flags
    });
};

/**
 * Fetches metadata optimized for streaming or download workflows.
 *
 * Differences from getInfo():
 * - Allows explicit control over playlist flattening.
 * - Can return full video URLs when preparing for downloads.
 *
 * Typical use cases:
 * - Streaming pipelines
 * - Download queues
 * - Playlists where each entry must be resolved individually
 *
 * @param {string | URL} url
 *   The YouTube video or playlist URL.
 *
 * @param {Object} [options={}]
 * @param {boolean} [options.forDownload=false]
 *   If true, disables playlist flattening to preserve full video URLs.
 *
 * @param {Object} [options.flags]
 *   Additional yt-dlp flags.
 *
 * @returns {Promise<Object>}
 *   Parsed metadata JSON returned by yt-dlp.
 */
const getInfoForStream = (url, { forDownload = false, ...flags } = {}) => {
    const isPlaylist = url.includes('list=');

    return youtubedl(url, {
        dumpSingleJson: true,
        skipDownload: true,
        jsRuntimes: 'node',

        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        socketTimeout: 30,
        concurrentFragments: 1,

        userAgent:
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',

        ...(isPlaylist && !forDownload ? { flatPlaylist: true } : {}),
        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),
        ...flags
    });
};

/**
 * Downloads a YouTube video using previously extracted metadata.
 *
 * This method separates metadata extraction from the download phase,
 * which:
 * - Reduces repeated scraping
 * - Improves reliability
 * - Allows metadata caching strategies
 *
 * @param {string} infoFile
 *   Path to a JSON file generated by getInfo() or getInfoForStream().
 *
 * @param {Object} [flags={}]
 *   Additional yt-dlp flags (format selection, output template, etc.).
 *
 * @returns {Promise<void>}
 */
const fromInfo = (infoFile, flags = {}) => {
    return youtubedl.exec('', {
        loadInfoJson: infoFile,
        jsRuntimes: 'node',

        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        concurrentFragments: 1,

        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),
        ...flags
    });
};

module.exports = {
    getInfo,
    getInfoForStream,
    fromInfo
};
