const youtubedl = require('youtube-dl-exec');
const path = require('path');

/**
 * Optional path to a cookies file for authenticated YouTube access.
 * Can be stored in your repository or as a secret in deployment environments.
 */
const COOKIES_PATH = path.join(__dirname, 'cookies.txt');

/**
 * Fetches metadata from a YouTube video or playlist WITHOUT downloading media.
 *
 * This function:
 * - Returns metadata as JSON.
 * - Forces Node.js as the JavaScript runtime for yt-dlp.
 * - Uses anti-block strategies to reduce the risk of being blocked by YouTube.
 * - Supports playlists by flattening if needed.
 * - Optionally uses cookies for authenticated access.
 *
 * @param {string | URL} url - The YouTube video or playlist URL.
 * @param {Object} [flags={}] - Additional yt-dlp flags to override defaults.
 * @returns {Promise<Object>} - Parsed metadata JSON from yt-dlp.
 */
const getInfo = (url, flags = {}) => {
    const isPlaylist = url.includes('playlist') || url.includes('list=');

    return youtubedl(url, {
        dumpSingleJson: true,
        skipDownload: true,
        jsRuntimes: 'node',

        // Anti-block strategy
        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        socketTimeout: 30,
        concurrentFragments: 1,

        // Browser fingerprint
        userAgent:
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',

        ...(isPlaylist ? { flatPlaylist: true } : {}),

        // Use cookies if available
        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),

        ...flags
    });
};

/**
 * Fetches metadata optimized for streaming or download workflows.
 *
 * Differences from getInfo():
 * - Allows controlling whether playlist entries are flattened.
 * - Supports use cases where full video URLs are required (e.g., downloading).
 *
 * @param {string | URL} url - The YouTube video or playlist URL.
 * @param {Object} [options={}] - Options for fetching metadata.
 * @param {boolean} [options.forDownload=false] - If true, returns full video URLs instead of flat IDs.
 * @param {Object} [options.flags] - Additional yt-dlp flags.
 * @returns {Promise<Object>} - Parsed metadata JSON from yt-dlp.
 */
const getInfoForStream = (url, { forDownload = false, ...flags } = {}) => {
    const isPlaylist = url.includes('list=');

    return youtubedl(url, {
        dumpSingleJson: true,
        skipDownload: true,
        jsRuntimes: 'node',

        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        socketTimeout: 30,
        concurrentFragments: 1,

        userAgent:
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',

        ...(isPlaylist && !forDownload ? { flatPlaylist: true } : {}),
        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),
        ...flags
    });
};

/**
 * Downloads a YouTube video using previously saved metadata from a JSON file.
 *
 * This separates metadata extraction from downloading, minimizing repeated scraping.
 *
 * @param {string} infoFile - Path to a JSON file generated by getInfo().
 * @param {Object} [flags={}] - Additional yt-dlp flags (format, output template, etc.).
 * @returns {Promise<void>}
 */
const fromInfo = (infoFile, flags = {}) => {
    return youtubedl.exec('', {
        loadInfoJson: infoFile,
        jsRuntimes: 'node',
        sleepInterval: 3,
        maxSleepInterval: 8,
        retries: 2,
        fragmentRetries: 2,
        concurrentFragments: 1,
        ...(COOKIES_PATH ? { cookies: COOKIES_PATH } : {}),
        ...flags
    });
};

module.exports = {
    getInfo,
    getInfoForStream,
    fromInfo
};
