const fs = require('fs');
const path = require('path');
const { downloadWithProgress } = require('../helpers/progress-bar');

/**
 * Express route handler to download a YouTube video using a previously saved info JSON.
 *
 * Expects the request body to contain:
 * - `outputPath`: Directory where the video will be saved.
 * - `filename`: Optional custom filename for the video.
 * - `infoId`: ID of the JSON file with video info (generated by infoVideo).
 * - `formatId`: Format code for the video download.
 *
 * Sends a fast JSON response to the client confirming the download started,
 * then downloads the video in the background while showing progress in the console.
 *
 * @param {import('express').Request} req - Express request object
 * @param {import('express').Response} res - Express response object
 * @returns {Promise<void>} Resolves after downloadWithProgress finishes
 *
 * @example
 * POST /download-video
 * {
 *   "outputPath": "./downloads",
 *   "filename": "myvideo.mp4",
 *   "infoId": "abc123",
 *   "formatId": "22"
 * }
 */
const downloadVideo = async (req, res) => {
    try {
        const { outputPath, filename, infoId, formatId } = req.body;

        if (!outputPath || !infoId || !formatId) {
            return res.status(400).json({ error: 'outputPath, infoId and formatId are required' });
        }

        const infoPath = `./tmp/${infoId}.json`;

        if (!fs.existsSync(infoPath)) {
            return res.status(404).json({ error: 'Info JSON not found' });
        }

        const info = JSON.parse(fs.readFileSync(infoPath, 'utf-8'));

        if (!info.formats?.some(f => f.format_id === formatId)) {
            return res.status(400).json({ error: `Format ${formatId} not available for this video` });
        }

        if (info._type && info._type !== 'video') {
            return res.status(400).json({ error: 'Provided info JSON is not a video' });
        }

        // Clean title to avoid invalid filename characters
        const safeTitle = info.title.replace(/[<>:"/\\|?*]/g, '').trim();
        const finalName = filename || `${safeTitle}.mp4`;
        const downloadUserPath = path.join(outputPath, finalName);

        // Fast response to client
        res.json({ message: 'Download started', path: downloadUserPath });

        // Start actual download with progress
        await downloadWithProgress(infoPath, {
            format: `${formatId}`,
            output: downloadUserPath
        });
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: err.message });
    }
};

module.exports = { downloadVideo };
